ENT.Base = "base_ai"
ENT.Type = "ai"
ENT.PrintName = "Hostile Rat"
ENT.Category = "Rat"
ENT.Author = "SMOK"
ENT.Contact = "https://steamcommunity.com/id/dany990011"
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true 
ENT.AdminOnly = false 